from pox.core import core
import pox.openflow.libopenflow_01 as of
from pox.lib.packet.ipv4 import ipv4
from pox.lib.packet.tcp import tcp
from pox.lib.packet.arp import arp
from pox.lib.packet.ethernet import ethernet
from pox.lib.recoco import Timer
from pox.lib.util import dpid_to_str

# [ TO - DO ]: Remove the following comment to use the 2nd version of the script
# import networkx as nx

import os
import time
import logging

# Forcing the Italian time zone for consistent logs
os.environ[ "TZ" ] = "Europe/Rome"
time.tzset()

# Silencing annoying system unpacking errors
logging.getLogger( "packet" ).setLevel( logging.WARNING )

# Silencing chatty LLDP messages from the discovery module
logging.getLogger( "openflow.discovery" ).setLevel( logging.WARNING )

log = core.getLogger()

class Project_1( object ):
    def __init__( self, burst, capacity, collectors, cutoff, hard, idle, inactivity, k, period, version ):

        # Purpose: It initializes the SDN component to orchestrate the ML trainings

        # Listening to OpenFlow events generated by switches
        core.openflow.addListeners( self )

        self.version = int( version )
        log.info( "Starting Project_1 using mode: %s", self.version )
        
        # Initializing the global topology based on the selected version ( 1 -> UCMP, 2 -> via "networkx" library )
        if self.version == 1:
            self.topology = {} # as an adjacency dictionary ( e.g., self.topology[ dpid1 ][ dpid2 ] = out_port )
        else:
            self.topology = nx.DiGraph() 
        
        # Dynamic host tracking: IP map -> ( edge switch DPID, in_port, MAC )
        self.ip_to_location = {}

        self.capacity = int( capacity )
        
        # Preparing an empty dictionary to track traffic currently routed on links ( Capacity-Awareness )
        self.link_allocated_rate = {}

        # Cache to prevent a worker from changing paths while it is transmitting data
        # Stores a tuple: (selected_path, worker_expected_rate) for accurate Traffic Control freeing
        self.assigned_paths = {}
        
        # Parsing of collectors eventually passed to "launch" via CLI
        self.collectors = {}

        if collectors:
            for item in collectors.split( "," ):
                ip, name = item.split( ":" )
                self.collectors[ ip ] = name
        
        log.info( "Collectors: %s", self.collectors )

        # Operating parameters
        self.burst = float( burst ) # Byte/s threshold to detect incast
        self.cutoff = int( cutoff ) # Maximum path search depth
        self.idle = int( idle ) # OpenFlow inactivity timeout
        self.hard = int( hard ) # OpenFlow forced expiration limit
        self.k = int( k ) # Maximum number of paths ( K-Shortest Paths )
        self.period = float( period ) # Polling frequency

        self.inactivity = inactivity
        
        # Variables to align the Phase visually with the traffic generator execution
        self.first_burst_detected = False
        self.global_start_time = 0.0
        
        # Data structure for retaining traffic progress and statistics 
        self.trainings = {
            c: {
                "Workers": set(), # Set of all workers viewed
                "Active_This_Round": set(), # Workers currently transmitting
                "Worker_Bytes": {}, # Historical byte buffer for each worker
                "Dv": 0, # Volume of data in the current round
                "Last_Dv": 0, # Persistent volume of the PREVIOUS round
                "Duration": 0, # Physical duration of the burst
                "Tv_Period": 0.0, # Period between the start of rounds
                "Phase": -1.0, # Fixed time when training procedure starts
                "Last_Time": time.time(), # Last polling timestamp
                "In_Burst": False, # State
                "Silence_Count": 0, # Tolerance mechanism for TCP RTO
                "Round": 0, # Global iteration counter
                "Last_Round_Start": 0.0, # Helper to calculate Tv_Period
                "Last_Activity_Time": time.time()
            } for c in self.collectors
        }

        # Elements for behavioral optimizations
        self.path_cache = {} # Path caching to save CPU     
        self.installed_flows = {} # Anti-Storm for Packet-Ins ( memoization )     
        
        # Listening to the "openflow.discovery" module to update the links
        def bind_discovery():
            core.openflow_discovery.addListeners( self )
        core.call_when_ready( bind_discovery, "openflow_discovery" )
        
        # Start an asynchronous timer to query for status every "period" seconds
        Timer( self.period, self.requestStatistics, recurring = True )

    # MODULE 1: Topology & Host Discovery
    def _handle_LinkEvent( self, event ):

        # Purpose: It manages both topology and host discovery, updating the reference ( according to the version ) whenever an internal link is detected ( or falls )

        link = event.link

        if event.added:
            if self.version == 1:
                if link.dpid1 not in self.topology: self.topology[ link.dpid1 ] = {}
                if link.dpid2 not in self.topology: self.topology[ link.dpid2 ] = {}
                self.topology[ link.dpid1 ][ link.dpid2 ] = link.port1
                self.topology[ link.dpid2 ][ link.dpid1 ] = link.port2
            else:
                self.topology.add_edge( link.dpid1, link.dpid2, port = link.port1 )
                self.topology.add_edge( link.dpid2, link.dpid1, port = link.port2 )
            log.debug( "+ Link: %s <-> %s", dpid_to_str( link.dpid1 ), dpid_to_str( link.dpid2 ) )

            # Purge mistakenly learned hosts on newly discovered internal links (Convergence Fix)
            to_delete = []
            for ip, loc in self.ip_to_location.items():
                dpid, port, _ = loc
                if ( dpid == link.dpid1 and port == link.port1 ) or \
                   ( dpid == link.dpid2 and port == link.port2 ):
                    to_delete.append( ip )
            
            for ip in to_delete:
                del self.ip_to_location[ ip ]
                log.info( "Host %s removed from cache (port discovered as internal).", ip )

        elif event.removed:
            if self.version == 1:
                if link.dpid1 in self.topology and link.dpid2 in self.topology[ link.dpid1 ]:
                    del self.topology[ link.dpid1 ][ link.dpid2 ]
                    log.debug( "- Link: %s -> %s", dpid_to_str( link.dpid1 ), dpid_to_str( link.dpid2 ) )
                
                if link.dpid2 in self.topology and link.dpid1 in self.topology[ link.dpid2 ]:
                    del self.topology[ link.dpid2 ][ link.dpid1 ]
                    log.debug( "- Link: %s -> %s", dpid_to_str( link.dpid2 ), dpid_to_str( link.dpid1 ) )
            else:
                if self.topology.has_edge( link.dpid1, link.dpid2 ):
                    self.topology.remove_edge( link.dpid1, link.dpid2 )
                    log.debug( "- Link: %s -> %s", dpid_to_str( link.dpid1 ), dpid_to_str( link.dpid2 ) )
                
                if self.topology.has_edge( link.dpid2, link.dpid1 ):
                    self.topology.remove_edge( link.dpid2, link.dpid1 )
                    log.debug( "- Link: %s -> %s", dpid_to_str( link.dpid2 ), dpid_to_str( link.dpid1 ) )
                
            # Note: The cache must be erased because the topology changed ( paths must be computed again )
            self.path_cache.clear()
            log.info( "Topology modified... Path cache emptied." )

    def _handle_ConnectionUp( self, event ):

        # Purpose: It registers the switch nodes in the network topology when they connect to the controller

        if self.version == 1:
            if event.dpid not in self.topology:
                self.topology[ event.dpid ] = {}
        else:
            if event.dpid not in self.topology:
                self.topology.add_node( event.dpid )

    def retrieveHostLocation( self, packet, event ):

        # Purpose: It dynamically learns the position of hosts on the network by intercepting ARP and IP addresses.

        if hasattr( core, "openflow_discovery" ):
            if not core.openflow_discovery.is_edge_port( event.dpid, event.port ):
                return

        # First, an internal double-check is provided for security reasons ( fallback )
        if event.dpid in self.topology:
            for neighbor in self.topology[ event.dpid ]:
                if self.version == 1:
                    internal_port = self.topology[ event.dpid ][ neighbor ]
                else:
                    internal_port = self.topology[ event.dpid ][ neighbor ][ "port" ]
                
                if event.port == internal_port:
                    return

        # Later, the effective learning occurs only if the IP is not already known
        if packet.type == ethernet.ARP_TYPE: 
            arp_packet = packet.payload
            
            if arp_packet.opcode in ( arp.REQUEST, arp.REPLY ):
                src_ip = str( arp_packet.protosrc )
                
                if src_ip not in self.ip_to_location:
                    self.ip_to_location[ src_ip ] = ( event.dpid, event.port, packet.src )
                
        elif packet.type == ethernet.IP_TYPE:
            ip_packet = packet.payload
            src_ip = str( ip_packet.srcip )
            
            if src_ip not in self.ip_to_location:
                self.ip_to_location[ src_ip ] = ( event.dpid, event.port, packet.src )

    def getUCMPRoutes( self, src, dst, k, cutoff ):

        # Purpose: It computes up to k paths of varying lengths using DFS, avoiding routing loops while guaranteeing load balancing over asymmetric topologies

        if src == dst: 
            return [ [ src ] ]
            
        valid_paths = []
        
        def dfs( current_node, current_path ):
            # Note: the algorithm must stop if the desired maximum number of paths has already been found
            if len( valid_paths ) >= k: 
                return
                
            # If the destination is reached, save the path
            if current_node == dst:
                valid_paths.append( current_path )
                return
                
            # Furthermore, whenever the path gets too long, abandon it to prevent wandering
            if len( current_path ) > cutoff:
                return
                
            for neighbor in self.topology[ current_node ]:
                # Note: Only visit neighbors not yet in the current path must be considered to avoid infinite loops
                if neighbor not in current_path:
                    dfs( neighbor, current_path + [ neighbor ] )

        dfs( src, [ src ] )
        
        # Sort paths by length so shorter, more efficient routes are prioritized in the Round-Robin
        valid_paths.sort( key = len )
        return valid_paths

    def purgeFlows( self, dst_ip ):
        
        # Purpose: Forcefully removes physical flows from all switches for a given collector.
        # This guarantees that the next cycle forces a fresh PacketIn to get precise load-balanced routing.
        for conn in core.openflow.connections:
            
            # Remove forward flows
            msg = of.ofp_flow_mod()
            msg.command = of.OFPFC_DELETE
            msg.match.dl_type = 0x0800
            msg.match.nw_dst = dst_ip
            conn.send( msg )
            
            # Remove reverse (ACK) flows
            msg_rev = of.ofp_flow_mod()
            msg_rev.command = of.OFPFC_DELETE
            msg_rev.match.dl_type = 0x0800
            msg_rev.match.nw_src = dst_ip
            conn.send( msg_rev )

    # MODULE 2: Worker Discovery
    def _handle_PacketIn( self, event ):

        # Purpose: It analyzes new flows that do not match table rules

        packet = event.parsed

        if not packet.parsed: 
            return

        # Tracing the source host
        self.retrieveHostLocation( packet, event )

        if packet.type == ethernet.ARP_TYPE:
            arp_packet = packet.payload
            
            # 1. ARP PROXY: If we already know the destination IP, the controller responds directly!
            if arp_packet.opcode == arp.REQUEST:
                target_ip = str( arp_packet.protodst )
                if target_ip in self.ip_to_location:
                    _, _, target_mac = self.ip_to_location[ target_ip ]
                    
                    arp_reply = arp()
                    arp_reply.hwsrc = target_mac
                    arp_reply.hwdst = arp_packet.hwsrc
                    arp_reply.opcode = arp.REPLY
                    arp_reply.protosrc = arp_packet.protodst
                    arp_reply.protodst = arp_packet.protosrc
                    
                    ether = ethernet()
                    ether.type = ethernet.ARP_TYPE
                    ether.dst = packet.src
                    ether.src = target_mac
                    ether.payload = arp_reply
                    
                    msg = of.ofp_packet_out()
                    msg.data = ether.pack()
                    msg.actions.append( of.ofp_action_output( port = event.port ) )
                    event.connection.send( msg )
                    return
                    
            # 2. ARP REPLY UNICAST: Do not flood replies, send them directly
            elif arp_packet.opcode == arp.REPLY:
                target_ip = str( arp_packet.protodst )
                if target_ip in self.ip_to_location:
                    tgt_dpid, tgt_port, _ = self.ip_to_location[ target_ip ]
                    if tgt_dpid in core.openflow.connections:
                        msg = of.ofp_packet_out()
                        msg.data = event.ofp
                        msg.actions.append( of.ofp_action_output( port = tgt_port ) )
                        core.openflow.connections[ tgt_dpid ].send( msg )
                return

            # 3. SMART EDGE-FLOODING: If we do not know it, we send the ARP
            # EXCLUSIVELY to the hosts, bypassing the Spine links.
            for dpid in self.topology:
                if dpid not in core.openflow.connections: continue
                conn = core.openflow.connections[ dpid ]
                
                # Identify internal ports (connected to other switches)
                internal_ports = set()
                if dpid in self.topology:
                    if self.version == 1:
                        internal_ports = set( self.topology[ dpid ].values() )
                    else:
                        for neighbor in self.topology[ dpid ]:
                            internal_ports.add( self.topology[ dpid ][ neighbor ][ "port" ] )
                
                # Flood ONLY on outward-facing ports (Workers)
                for port_no in conn.ports:
                    if port_no < of.OFPP_MAX and port_no not in internal_ports:
                        if dpid == event.dpid and port_no == event.port: continue # Do not send back
                        
                        msg = of.ofp_packet_out()
                        msg.data = event.ofp
                        msg.actions.append( of.ofp_action_output( port = port_no ) )
                        conn.send( msg )
            return

        # Extracting the IP and TCP information
        ip_packet = packet.find( "ipv4" ) 
        tcp_packet = packet.find( "tcp" )

        if ip_packet and tcp_packet:
            src_ip = str( ip_packet.srcip )
            dst_ip = str( ip_packet.dstip )
            
            # If traffic is directed to a collector,
            if dst_ip in self.collectors:
                training_data = self.trainings[ dst_ip ]

                # the relative worker must be inserted ( if not previously done )
                if src_ip not in training_data[ "Workers" ]:
                    training_data[ "Workers" ].add( src_ip )
                    log.info( "New Worker %s added to %s.", src_ip, self.collectors[ dst_ip ] )
                
                if dst_ip not in self.ip_to_location:
                    # Prevent Broadcast Storm: Do not flood unknown IP packets. TCP will retransmit.
                    return

                # ( in any case ) the routing module is triggered to install the path
                self.installRoute( event.dpid, src_ip, dst_ip, training_data )

    # MODULE 3: Traffic Characterization
    def requestStatistics( self ):

        # Purpose: It sends status requests to datapaths for measuring flows and eventually reset them due to inactivity

        for connection in core.openflow.connections:
            connection.send( of.ofp_stats_request( body = of.ofp_flow_stats_request() ) )

        current_time = time.time()

        for key, data in self.trainings.items():
            if data[ "Phase" ] > -1.0 and ( current_time - data[ "Last_Activity_Time" ] ) > self.inactivity:
                log.info( "Procedure %s finished. Global reset.", self.collectors[ key ] )
                
                # Free bandwidth allocations specific to this training's workers
                for w in data[ "Workers" ]:
                    if w in self.assigned_paths:
                        p, r = self.assigned_paths[ w ]
                        for i in range( len( p ) - 1 ):
                            edge = ( p[ i ], p[ i + 1 ] )
                            if edge in self.link_allocated_rate:
                                self.link_allocated_rate[ edge ] = max( 0.0, self.link_allocated_rate[ edge ] - r )
                        del self.assigned_paths[ w ]

                # Physically purge flows to clean up the network
                self.purgeFlows( key )

                data[ "Round" ] = 0
                data[ "Workers" ].clear()
                data[ "Active_This_Round" ].clear()
                data[ "Worker_Bytes" ].clear()
                data[ "Dv" ] = 0
                data[ "Last_Dv" ] = 0
                data[ "Duration" ] = 0
                data[ "Tv_Period" ] = 0.0
                data[ "Phase" ] = -1.0
                data[ "Last_Round_Start" ] = 0.0
                data[ "Last_Activity_Time" ] = current_time
                data[ "In_Burst" ] = False
                data[ "Silence_Count" ] = 0

    def _handle_FlowStatsReceived( self, event ):

        # Purpose: It receives and analyzes OpenFlow statistics

        current_time = time.time()
        
        for dst_ip in self.collectors:

            # Note: Edge polling mechanism to filter the indicators that allows to process only those coming from the switch directly connected to the destination element ( intermidiate devices are ignored )
            if dst_ip not in self.ip_to_location:
                continue

            dest_dpid = self.ip_to_location[ dst_ip ][ 0 ]

            if event.connection.dpid != dest_dpid:
                continue 
            
            training_data = self.trainings[ dst_ip ]
            bytes_difference = 0
            active_in_cycle = set()
            
            # Grouping bytes by source IP to prevent double counting of concurrent flows
            current_worker_bytes = {}
            for f in event.stats:
                if f.match.nw_src and f.match.nw_dst == dst_ip:
                    src_ip = str( f.match.nw_src )
                    current_worker_bytes[ src_ip ] = current_worker_bytes.get( src_ip, 0 ) + f.byte_count
            
            for src_ip, total_bytes in current_worker_bytes.items():
                last_b = training_data[ "Worker_Bytes" ].get( src_ip, 0 )

                # Handling OpenFlow rules timeout. If "byte_count" is reset, computations start from 0
                if total_bytes >= last_b:
                    diff = total_bytes - last_b
                else:
                    diff = total_bytes 
                    
                bytes_difference += diff
                training_data[ "Worker_Bytes" ][ src_ip ] = total_bytes
                
                if diff > 0:
                    active_in_cycle.add( src_ip )
                    
            time_difference = current_time - training_data[ "Last_Time" ]
            
            if time_difference > 0:
                throughput = bytes_difference / time_difference

                if throughput > ( self.burst * 0.05 ):
                    training_data[ "Last_Activity_Time" ] = current_time
                
                if throughput > self.burst: 
                    # If the rate exceeds the threshold, a burst occurs, raising an incast aggregation phase
                    if not training_data[ "In_Burst" ]:
                        training_data[ "In_Burst" ] = True
                        
                        # Set the master clock if this is the absolute first traffic detected across the network
                        if not self.first_burst_detected:
                            self.first_burst_detected = True
                            self.global_start_time = current_time

                        if training_data[ "Last_Round_Start" ] > 0:
                            training_data[ "Tv_Period" ] = current_time - training_data[ "Last_Round_Start" ]

                        training_data[ "Last_Round_Start" ] = current_time
                        
                        # Note: The phase is fixed and never overwritten again (-1 indicates it hasn't been set)
                        if training_data[ "Phase" ] == -1.0:
                            training_data[ "Phase" ] = current_time - self.global_start_time
                        
                        training_data[ "Duration" ] = 0
                        training_data[ "Dv" ] = 0
                        training_data[ "Active_This_Round" ].clear()

                    # Reset silence count explicitly
                    training_data[ "Silence_Count" ] = 0
                    
                    # Updating the statistics
                    training_data[ "Dv" ] += bytes_difference
                    training_data[ "Duration" ] += time_difference
                    training_data[ "Active_This_Round" ].update( active_in_cycle )

                else:
                    if training_data[ "In_Burst" ]:
                        # Accumulate straggler bytes arriving during TCP RTO pauses
                        training_data[ "Dv" ] += bytes_difference
                        training_data[ "Duration" ] += time_difference
                        training_data[ "Active_This_Round" ].update( active_in_cycle )
                        
                        training_data[ "Silence_Count" ] += 1
                        
                        # Apply Grace Period to prevent premature splitting
                        if training_data[ "Silence_Count" ] >= 2:
                            training_data[ "In_Burst" ] = False
                            training_data[ "Silence_Count" ] = 0
                            
                            d_v = training_data[ "Dv" ]
                            d_v_mb = d_v / 1000000.0  # Convert volume to MB
                            
                            # Ignore trivial TCP ACKs phantom rounds (must be > 1 MB)
                            if d_v_mb > 1.0:
                                training_data[ "Round" ] += 1
                                current_round = training_data[ "Round" ]
                                active_workers = list( training_data[ "Active_This_Round" ] )
                                k_v = len( active_workers )
                                t_v = training_data[ "Tv_Period" ]
                                phi_v = training_data[ "Phase" ]
                                training_name = self.collectors[ dst_ip ]

                                log.info( "=" * 55 )
                                log.info( "[ %s ] - ROUND %d COMPLETED", training_name, current_round )
                                log.info( "Workers (K_v) : %d  -> %s", k_v, active_workers )
                                log.info( "Volume (D_v)  : %.2f MB", d_v_mb ) 
                                log.info( "Period (T_v)  : %.2f sec", t_v )
                                log.info( "Phase (Phi_v) : %.2f sec", phi_v )
                                log.info( "=" * 55 )
                                
                                # Store the reliable volume of this round for future TC estimations
                                training_data[ "Last_Dv" ] = d_v

                                # Free bandwidth allocations specifically for the workers of this round
                                for w in active_workers:
                                    if w in self.assigned_paths:
                                        p, r = self.assigned_paths[ w ]
                                        for i in range( len( p ) - 1 ):
                                            edge = ( p[ i ], p[ i + 1 ] )
                                            if edge in self.link_allocated_rate:
                                                self.link_allocated_rate[ edge ] = max( 0.0, self.link_allocated_rate[ edge ] - r )
                                        del self.assigned_paths[ w ]
                                        
                                # Physically purge flows to force next cycle to perform fresh Traffic Control routing
                                self.purgeFlows( dst_ip )

            training_data[ "Last_Time" ] = current_time

    # MODULE 4: Traffic Control & Routing 
    def installRoute( self, src_dpid, src_ip, dst_ip, training_data ):

        # Purpose: It calculates k-shortest paths with appropriate caching ( both flows & routes )
        
        # First, the "Period" of the burst is considered to dynamically adjust the OpenFlow timeouts
        estimated_tv = training_data[ "Tv_Period" ] if training_data[ "Tv_Period" ] > 0 else float( self.idle )
        
        # Then, the anti Packet-In storms mechanism is configured
        flow = ( src_ip, dst_ip )
        current_time = time.time()
        
        # If rules have already calculated and sent for the current flow in the last "period" seconds, block the request
        if flow in self.installed_flows:
            if current_time - self.installed_flows[ flow ] < self.period: 
                return

        # Later, an host tracking check is performed ( if it fails, the instance is left to forwarding.l2_learning until it is learnt via ARP )
        if dst_ip not in self.ip_to_location: 
            return
            
        dest_dpid, dest_port, _ = self.ip_to_location[ dst_ip ]

        # Note: the following statement avoids crashes if the topology is not yet fully formed
        if src_dpid not in self.topology or dest_dpid not in self.topology: 
            return

        path = ( src_dpid, dest_dpid )

        if path not in self.path_cache:
            if self.version == 1:
                k_paths = self.getUCMPRoutes( src_dpid, dest_dpid, k = self.k, cutoff = self.cutoff )
                
                if not k_paths: 
                    log.warning( "Routing Error: No valid path between DPIDs %s e %s", src_dpid, dest_dpid )
                    return
                
                self.path_cache[ path ] = k_paths
            else:
                try:
                    # Note: It executes the algorithm iff the path is not within the cache
                    # Then, it searchs all paths ( even non-minimum ones ) within a certain-hop cutoff to prevent packets from wandering endlessly in huge topologies
                    paths = list( nx.all_simple_paths( self.topology, source = src_dpid, target = dest_dpid, cutoff = self.cutoff ) )
                    
                    # Finally, the list is sorted so that the shortest-paths first approach can still be exploited, but also include the longest ones if necessary to get to k
                    paths.sort( key = len )

                    self.path_cache[ path ] = paths[ :self.k ] # at most k options are being stored
                    log.debug( "New paths among DPIDs %s e %s", src_dpid, dest_dpid )
                except nx.NetworkXNoPath:
                    log.warning( "Routing Error: No valid path between DPIDs %s e %s", src_dpid, dest_dpid )
                    return

        k_paths = self.path_cache[ path ]

        if not k_paths: 
            return

        # Finally, the Capacity-Aware engine is launched to provide a fair global balancing
        if src_ip in self.assigned_paths:
            selected_path = self.assigned_paths[ src_ip ][ 0 ]
        else:
            # Note: "Active_This_Round" is used to estimate capacity if available, otherwise fallback to history
            active_set = training_data.get( "Active_This_Round", set() )
            K_v = len( active_set ) if len( active_set ) > 0 else len( training_data.get( "Workers", set() ) )
            
            # Prevent negative feedback loop: distribute capacity evenly among workers
            K_v = max( 1, K_v )
            worker_expected_rate = self.capacity / float( K_v )
            
            selected_path = k_paths[ 0 ]
            min_bottleneck = float( "inf" )

            # Finding the least saturated path virtually
            for p in k_paths:
                path_bottleneck = 0.0

                for i in range( len( p ) - 1 ):
                    edge = ( p[ i ], p[ i + 1 ] )

                    current_load = self.link_allocated_rate.get( edge, 0.0 )
                    saturation = ( ( current_load + worker_expected_rate ) / float( self.capacity ) ) * 100
                    
                    if saturation > path_bottleneck: 
                        path_bottleneck = saturation
                
                if path_bottleneck < min_bottleneck:
                    min_bottleneck = path_bottleneck
                    selected_path = p

            # Updating the network balance incrementally
            for i in range( len( selected_path ) - 1 ):
                edge = ( selected_path[ i ], selected_path[ i + 1 ] )
                self.link_allocated_rate[ edge ] = self.link_allocated_rate.get( edge, 0.0 ) + worker_expected_rate

            self.assigned_paths[ src_ip ] = ( selected_path, worker_expected_rate )
            
            hex_path = [ dpid_to_str( node ) for node in selected_path ]
            
            log.info( "ROUTING [%s] | %s -> %s | Path: %s | Saturation: %5.2f%%", self.collectors[ dst_ip ].replace( "Training_", "" ).upper(), src_ip, dst_ip, hex_path, min_bottleneck )

        # The function ends with:
        # -) Installing ofp_flow_mod along all intermediate nodes of the route
        for i in range( len( selected_path ) - 1 ):
            current_node = selected_path[ i ]
            next_node = selected_path[ i + 1 ]

            if self.version == 1:
                out_port = self.topology[ current_node ][ next_node ]
            else:
                out_port = self.topology[ current_node ][ next_node ][ "port" ]

            self.sendFlowMod( current_node, src_ip, dst_ip, out_port, estimated_tv )
        
        # -) Storing the last rule on the switch that connects directly to the collector
        self.sendFlowMod( dest_dpid, src_ip, dst_ip, dest_port, estimated_tv )
        
        # =========================================================
        # 🔄 SYMMETRIC ROUTING: Install the return route (ACK)
        # =========================================================
        if src_ip in self.ip_to_location:
            src_dpid_loc, src_port_loc, _ = self.ip_to_location[ src_ip ]
            reversed_path = selected_path[::-1] # Reverse the path list
            
            # Install the return rules on the intermediate nodes
            for i in range( len( reversed_path ) - 1 ):
                current_node = reversed_path[ i ]
                next_node = reversed_path[ i + 1 ]
                
                if self.version == 1:
                    out_port = self.topology[ current_node ][ next_node ]
                else:
                    out_port = self.topology[ current_node ][ next_node ][ "port" ]
                    
                self.sendReverseFlowMod( current_node, dst_ip, src_ip, out_port, estimated_tv )
                
            # Final rule on the switch connected to the Worker
            self.sendReverseFlowMod( src_dpid_loc, dst_ip, src_ip, src_port_loc, estimated_tv )
        # =========================================================
        
        self.installed_flows[ flow ] = current_time

    def sendReverseFlowMod( self, dpid, src_ip, dst_ip, out_port, estimated_tv ):

        # Purpose: Installs the symmetric return path for TCP ACKs (Collector -> Worker)
        connection = core.openflow.getConnection( dpid )

        if not connection: 
            return
            
        msg = of.ofp_flow_mod() 
        msg.priority = 65530 # Priority slightly lower than the forward path
        msg.match.dl_type = 0x0800 # IPv4
        msg.match.nw_src = src_ip # IP del Collector
        msg.match.nw_dst = dst_ip # IP del Worker
        
        # No TCP port here: let all responses return
        msg.idle_timeout = max( int( estimated_tv * 1.5 ), self.idle ) 
        msg.hard_timeout = self.hard 
        
        msg.actions.append( of.ofp_action_output( port = out_port ) ) 
        connection.send( msg )

    def sendFlowMod( self, dpid, src_ip, dst_ip, out_port, estimated_tv ):

        # Purpose: It creates and sends the OpenFlow Flow-Mod message to the specified switch

        connection = core.openflow.getConnection( dpid )

        if not connection: 
            return
            
        msg = of.ofp_flow_mod() 
        msg.priority = 65535 # High priority to override forwarding.l2_learning
        msg.match.dl_type = 0x0800 # Ethernet type IPv4 
        msg.match.nw_src = src_ip # Source IP ( Worker )
        msg.match.nw_dst = dst_ip # Destination IP ( Collector )
        
        msg.idle_timeout = max( int( estimated_tv * 1.5 ), self.idle ) # Remove unused rules after tot. seconds
        msg.hard_timeout = self.hard # Force expiration to allow continuous rebalancing
        
        msg.actions.append( of.ofp_action_output( port = out_port ) ) 
        connection.send( msg )

def launch( burst = 100000, capacity = 12500000, collectors = "10.0.1.1:Training_Blue,10.0.1.2:Training_Green,10.0.1.3:Training_Red,10.0.1.4:Training_Yellow", cutoff = 3, hard = 0, idle = 10, inactivity = 120, k = 2, period = 1, version = 1 ):
    
    # Purpose: It represents the POX entry point. Parameters can be injected using the command line
    
    core.registerNew( Project_1, burst, capacity, collectors, cutoff, hard, idle, inactivity, k, period, version )