# Define the images for all nodes.
# Hosts use the base image, while network nodes and sfs require a P4-compatible image.
h1[image]="kathara/base"
h2[image]="kathara/base"
h3[image]="kathara/base"
h4[image]="kathara/base"

a[image]="kathara/p4"
b[image]="kathara/p4"
c[image]="kathara/p4"
d[image]="kathara/p4"
e[image]="kathara/p4"
f[image]="kathara/p4"
g[image]="kathara/p4"
h[image]="kathara/p4"

sf1[image]="kathara/p4"
sf2[image]="kathara/p4"
sf3[image]="kathara/p4"

# Connect End Hosts to edge switches
h1[0]="h1_a"
a[0]="h1_a"

h2[0]="h2_a"
a[1]="h2_a"

h3[0]="h3_h"
h[0]="h3_h"

h4[0]="h4_h"
h[1]="h4_h"

# Core network mesh connections
a[2]="a_b"
b[0]="a_b"

a[3]="a_c"
c[0]="a_c"

b[1]="b_c"
c[1]="b_c"

b[2]="b_d"
d[0]="b_d"

b[3]="b_f"
f[0]="b_f"

c[2]="c_e"
e[0]="c_e"

c[3]="c_g"
g[0]="c_g"

d[1]="d_f"
f[1]="d_f"

e[1]="e_g"
g[1]="e_g"

f[2]="f_g"
g[2]="f_g"

f[3]="f_h"
h[2]="f_h"

g[3]="g_h"
h[3]="g_h"

# Connect Service Functions to their respective Service Function Forwarders (sfFs)
sf1[0]="d_sf1"
d[2]="d_sf1"

sf2[0]="d_sf2"
d[3]="d_sf2"

sf3[0]="e_sf3"
e[2]="e_sf3"