from pox.core import core
import pox.openflow.libopenflow_01 as of
from pox.lib.packet.arp import arp
from pox.lib.packet.ethernet import ethernet
from pox.lib.recoco import Timer
from pox.lib.util import dpid_to_str
import os
import time
import logging
import shutil

# Forcing the Italian time zone for consistent logs
os.environ[ "TZ" ] = "Europe/Rome"
time.tzset()

# Silencing annoying system unpacking errors and chatty LLDP messages
logging.getLogger( "packet" ).setLevel( logging.CRITICAL )
logging.getLogger( "openflow.discovery" ).setLevel( logging.WARNING )

log = core.getLogger()

class Project_1( object ):
    def __init__( self, alpha, burst, capacity, collectors, cutoff, hard, inactivity, k, period, stability, start_phi ):

        # Purpose: It initializes the SDN component to orchestrate the ML trainings

        # Listening to OpenFlow events generated by switches
        core.openflow.addListeners( self )

        log.info( "[SYSTEM] Starting Project_1..." )
        
        # Initializing the global topology
        self.topology = {} 
        
        # Variables to monitor topology stability and inform the user when to run the "python3 incast_generator.py" command from the laboratory's home directory
        self.topology_stable = False
        self.topology_timer = None

        # Dynamic host tracking: IP map -> ( edge switch DPID, in_port, MAC )
        self.ip_to_location = {}
        self.capacity = int( capacity ) # the maximum physical bandwidth of network links ( in Bytes/s ). It is used by the Capacity-Aware engine to estimate saturation
        
        # Dictionary to track traffic currently routed on links ( Capacity-Awareness )
        self.link_allocated_rate = {}

        # Cache to prevent a worker from changing paths while it is transmitting data
        self.assigned_paths = {}
        
        # Parsing of collectors passed to "launch" via CLI
        self.collectors = {}

        if collectors:
            for item in collectors.split( "," ):
                ip, name = item.split( ":" )
                self.collectors[ ip ] = name.replace( "Training_", "" ).upper() # pre-formatting name for clean logs
        
        log.info( "[SYSTEM] Collectors: %s", self.collectors )

        # Operating parameters
        self.alpha = float ( alpha )
        self.burst = float( burst ) # the throughput threshold ( Bytes/s ) that triggers the "In_Burst" state, allowing the controller to detect the ML Incast
        self.cutoff = int( cutoff ) # the maximum hop depth allowed when searching for paths via DFS, preventing endless loops in large topologies
        self.hard = int( hard ) # OpenFlow hard timeout ( seconds ). Flow rules expire strictly after this time to force continuous traffic rebalancing
        self.k = int( k ) # the maximum number of redundant paths to compute and cache between any source and destination ( K-Shortest Paths )
        self.period = float( period ) # the polling interval ( seconds ) for the Controller to request traffic statistics from edge switches
        self.inactivity = int( inactivity ) # the absolute silence duration ( seconds ) required to declare a training procedure fully completed and trigger a global reset
        self.stability = int( stability )
        self.start_phi = float( start_phi )

        # Variables to align the "Phase" visually with the traffic generator execution
        self.first_burst_detected = False
        self.global_start_time = 0.0
        
        # Data structure for retaining traffic progress and orchestration statistics
        self.trainings = {
            collector: {
                "Workers": set(), # collection of all unique worker IPs associated with this specific collector
                "Active_This_Round": set(), # collection of workers that have been physically active during the current detected burst 
                "Worker_Bytes": {}, # internal buffer to store the last "byte_count" for each worker to calculate throughput deltas
                "Dv": 0, # total data volume ( Bytes ) transferred during the ongoing burst
                "Last_Dv": 0, # persistent storage of the data volume from the previous completed round for "Traffic Control"
                "Total_Accumulated_Bytes": 0, # lifetime counter of bytes sent by this training for the final report before global reset
                "Duration": 0, # physical duration ( seconds ) of the ongoing burst period
                "Tv_Period": 0.0, # estimated time interval between the start of consecutive training rounds ( T_v )
                "Phase": -1.0, # the time offset ( seconds ) between the global experiment start and the arrival of the first packet for this training
                "Last_Time": time.time(), # timestamp of the last polling cycle used to calculate the time_difference for throughput
                "In_Burst": False, # boolean flag indicating if the training is currently in an active Incast state
                "Silence_Count": 0, # counter used to grant a "grace period" during low throughput, preventing TCP RTO stalls from prematurely ending a round
                "Round": 0, # counter of successfully completed ML training cycles
                "Current_Burst_Start": 0.0, # temporary anchor storing the exact timestamp when the ongoing burst was first detected
                "Last_Real_Round_Start": 0.0, # persistent anchor storing the start timestamp of the last validated ML round to compute "Tv_Period"
                "Last_Activity_Time": time.time(), # timestamp of the absolute last packet seen for this training, used to trigger the inactivity-based global reset
                "First_Packet_Time": 0.0 # exact timestamp of the first packet ( SYN ) detected via PacketIn, used for "Phase" calculation
            } for collector in self.collectors
        }

        # Elements for behavioral optimizations
        self.path_cache = {}    
        self.installed_flows = {}   
        
        # Listening to the "openflow.discovery" module to update the links
        def bind_discovery():
            core.openflow_discovery.addListeners( self )
        core.call_when_ready( bind_discovery, "openflow_discovery" )
        
        # Start an asynchronous timer to query for status every "self.period" seconds
        Timer( self.period, self.requestStatistics, recurring = True )

    def resetTopologyTimer( self ):

        # Purpose: It resets the timer to detect topology stability
        
        if self.topology_stable:
            return
        
        if self.topology_timer:
            self.topology_timer.cancel()

        self.topology_timer = Timer( self.stability, self.declareTopologyStable )

    def declareTopologyStable( self ):

        # Purpose: It logs a message to inform the user that the topology is stable
        
        self.topology_stable = True
        log.info( "[SYSTEM] Topology stabilized! The incast generator can be launched." )

    # MODULE 1: Topology & Host Discovery
    def _handle_LinkEvent( self, event ):
        
        # Purpose: It manages both topology and host discovery, updating the reference whenever an internal link is detected ( or falls )
        
        self.resetTopologyTimer()
        
        link = event.link

        if event.added:
            if link.dpid1 not in self.topology: self.topology[ link.dpid1 ] = {}
            if link.dpid2 not in self.topology: self.topology[ link.dpid2 ] = {}
            self.topology[ link.dpid1 ][ link.dpid2 ] = link.port1
            self.topology[ link.dpid2 ][ link.dpid1 ] = link.port2

            log.info( "[+ LINK] %s %s <-> %s %s", dpid_to_str( link.dpid1 ), link.port1, dpid_to_str( link.dpid2 ), link.port2 )

            # Note: it purges mistakenly learned hosts on newly discovered internal links 
            to_delete = [ 
                ip for ip, location in self.ip_to_location.items() 
                    if ( location[ 0 ] == link.dpid1 and location[ 1 ] == link.port1 ) or 
                            ( location[ 0 ] == link.dpid2 and location[ 1 ] == link.port2 )
            ]
            
            for ip in to_delete:
                del self.ip_to_location[ ip ]

        elif event.removed:
            if link.dpid1 in self.topology and link.dpid2 in self.topology[ link.dpid1 ]:
                del self.topology[ link.dpid1 ][ link.dpid2 ]
                log.info( "[- LINK] %s %s <-> %s %s", dpid_to_str( link.dpid1 ), link.port1, dpid_to_str( link.dpid2 ), link.port2 )

            if link.dpid2 in self.topology and link.dpid1 in self.topology[ link.dpid2 ]:
                del self.topology[ link.dpid2 ][ link.dpid1 ]
                log.info( "[- LINK] %s %s <-> %s %s", dpid_to_str( link.dpid2 ), link.port2, dpid_to_str( link.dpid1 ), link.port1 )
                
            # Note: The cache must be erased because the topology changed
            self.path_cache.clear()
            log.info( "[SYSTEM] Topology modified... Path cache emptied." )

    def _handle_ConnectionUp( self, event ):

        # Purpose: It registers the switch nodes in the network topology when they connect to the controller
        
        self.resetTopologyTimer()
        
        if event.dpid not in self.topology:
            self.topology[ event.dpid ] = {}

    def retrieveHostLocation( self, packet, event ):

        # Purpose: It dynamically learns host positions by intercepting ARP and IP packets on edge ports
        
        if hasattr( core, "openflow_discovery" ):
            if not core.openflow_discovery.is_edge_port( event.dpid, event.port ):
                return

        # First, an internal double-check is provided for security reasons ( fallback )
        if event.dpid in self.topology:
            for neighbor in self.topology[ event.dpid ]:
                internal_port = self.topology[ event.dpid ]
                
                if type( internal_port ) == dict:
                    internal_port = internal_port[ neighbor ]
                
                if event.port == internal_port:
                    return

        # Later, the effective learning occurs only if the IP is not already known
        if packet.type == ethernet.ARP_TYPE: 
            arp_packet = packet.payload

            if arp_packet.opcode in ( arp.REQUEST, arp.REPLY ):
                src_ip = str( arp_packet.protosrc )
                if src_ip not in self.ip_to_location:
                    self.ip_to_location[ src_ip ] = ( event.dpid, event.port, packet.src )
                
        elif packet.type == ethernet.IP_TYPE:
            ip_packet = packet.payload
            src_ip = str( ip_packet.srcip )

            if src_ip not in self.ip_to_location:
                self.ip_to_location[ src_ip ] = ( event.dpid, event.port, packet.src )

    def getUCMPRoutes( self, src, dst, k, cutoff ):

        # Purpose: It computes up to k paths of varying lengths using DFS, avoiding routing loops while guaranteeing load balancing over asymmetric topologies
        
        if src == dst: 
            return [ [ src ] ]
            
        valid_paths = []
        
        def dfs( current_node, current_path ):
            # Note: the algorithm must stop if the desired maximum number of paths has already been found
            if len( valid_paths ) >= k: 
                return
            
            # If the destination is reached, save the path
            if current_node == dst:
                valid_paths.append( current_path )
                return
            
            # Furthermore, whenever the path gets too long, abandon it to prevent wandering
            if len( current_path ) > cutoff:
                return
                
            for neighbor in self.topology[ current_node ]:
                # Note: Only visited neighbors not yet in the current path must be considered to avoid infinite loops
                if neighbor not in current_path:
                    dfs( neighbor, current_path + [ neighbor ] )

        dfs( src, [ src ] )

        # Finally, it sorts paths by length in an ascending order
        valid_paths.sort( key = len )
        return valid_paths

    def purgeFlows( self, dst_ip ):

        # Purpose: It forcefully removes physical flows from all switches for a given collector, triggering fresh routing
        
        for connection in core.openflow.connections:
            # First, it starts with the cancellation of forward flows 
            msg = of.ofp_flow_mod()
            msg.command = of.OFPFC_DELETE
            msg.match.dl_type = 0x0800
            msg.match.nw_dst = dst_ip
            connection.send( msg )
            
            # Then, it proceeds by erasing the reversed ( ACK ) flows
            msg_rev = of.ofp_flow_mod()
            msg_rev.command = of.OFPFC_DELETE
            msg_rev.match.dl_type = 0x0800
            msg_rev.match.nw_src = dst_ip
            connection.send( msg_rev )

    # MODULE 2: Worker Discovery
    def _handle_PacketIn( self, event ):
        
        # Purpose: It analyzes new flows that do not match table rules and resolves ARP requests using a "proxy" strategy

        packet = event.parsed

        if not packet.parsed: 
            return

        # Tracing the source host
        self.retrieveHostLocation( packet, event )

        if packet.type == ethernet.ARP_TYPE:
            arp_packet = packet.payload
            
            # If the destination IP is already known, the controller replies directly
            if arp_packet.opcode == arp.REQUEST:
                target_ip = str( arp_packet.protodst )

                if target_ip in self.ip_to_location:
                    _, _, target_mac = self.ip_to_location[ target_ip ]
                    
                    arp_reply = arp()
                    arp_reply.hwsrc = target_mac
                    arp_reply.hwdst = arp_packet.hwsrc
                    arp_reply.opcode = arp.REPLY
                    arp_reply.protosrc = arp_packet.protodst
                    arp_reply.protodst = arp_packet.protosrc
                    
                    ether = ethernet()
                    ether.type = ethernet.ARP_TYPE
                    ether.dst = packet.src
                    ether.src = target_mac
                    ether.payload = arp_reply
                    
                    msg = of.ofp_packet_out()
                    msg.data = ether.pack()
                    msg.actions.append( of.ofp_action_output( port = event.port ) )
                    event.connection.send( msg )
                    return
                    
            # Note: Replies are not flooded. The controller sends them directly to the target
            elif arp_packet.opcode == arp.REPLY:
                target_ip = str( arp_packet.protodst )

                if target_ip in self.ip_to_location:
                    tgt_dpid, tgt_port, _ = self.ip_to_location[ target_ip ]

                    if tgt_dpid in core.openflow.connections:
                        msg = of.ofp_packet_out()
                        msg.data = event.ofp
                        msg.actions.append( of.ofp_action_output( port = tgt_port ) )
                        core.openflow.connections[ tgt_dpid ].send( msg )
                return

            # Conversely, if the address is unknown, it propagates ARP exclusively towards hosts, bypassing the spine links
            for dpid in self.topology:
                if dpid not in core.openflow.connections: 
                    continue

                conn = core.openflow.connections[ dpid ]
                
                internal_ports = set()
                if dpid in self.topology:
                    internal_ports = set( self.topology[ dpid ].values() )
                
                for port_no in conn.ports:
                    if port_no < of.OFPP_MAX and port_no not in internal_ports:
                        if dpid == event.dpid and port_no == event.port: continue 
                        
                        msg = of.ofp_packet_out()
                        msg.data = event.ofp
                        msg.actions.append( of.ofp_action_output( port = port_no ) )
                        conn.send( msg )
            return

        # Extracting the IP and TCP information
        ip_packet = packet.find( "ipv4" ) 
        tcp_packet = packet.find( "tcp" )

        if ip_packet and tcp_packet:
            src_ip = str( ip_packet.srcip )
            dst_ip = str( ip_packet.dstip )
            
            # If traffic is directed to a collector,
            if dst_ip in self.collectors:
                training_data = self.trainings[ dst_ip ]
                t_name = self.collectors[ dst_ip ]

                # Recording the timestamp to the millisecond of the very first packet ever
                if training_data[ "First_Packet_Time" ] == 0.0:
                    training_data[ "First_Packet_Time" ] = time.time()

                    # If this is the very first packet in the entire experiment, initialize time zero
                    if self.global_start_time == 0.0:
                        self.global_start_time = time.time()

                # the relative worker must be inserted ( if not previously done )
                if src_ip not in training_data[ "Workers" ]:
                    training_data[ "Workers" ].add( src_ip )
                    log.info( "[%s] NEW WORKER | %s successfully registered.", t_name, src_ip )
                
                # Preventing "Broadcast Storm". The controller does not flood unknown IP packets, forcing TCP to retransmit
                if dst_ip not in self.ip_to_location:
                    return

                # ( in any case ) the routing module is triggered to install the path
                self.installRoute( event.dpid, src_ip, dst_ip, training_data )

    # MODULE 3: Traffic Characterization
    def requestStatistics( self ):
        
        # Purpose: It sends status requests to datapaths for measuring flows and eventually resets them due to inactivity

        for connection in core.openflow.connections:
            connection.send( of.ofp_stats_request( body = of.ofp_flow_stats_request() ) )

        current_time = time.time()

        for key, data in self.trainings.items():
            if data[ "Phase" ] > -1.0 and ( current_time - data[ "Last_Activity_Time" ] ) > self.inactivity:
                
                t_name = self.collectors[ key ]
                total_mb = data[ "Total_Accumulated_Bytes" ] / 1000000.0
                
                term_width = shutil.get_terminal_size((85, 15)).columns - 15
                
                log.info( "-" * term_width )
                log.info( "[%s] TRAINING PROCEDURE COMPLETED", t_name )
                log.info( "[%s] Total Data Sent: %.2f MB", t_name, total_mb )
                log.info( "[%s] Reset Executed.", t_name )
                log.info( "-" * term_width )
                
                for worker in data[ "Workers" ]:
                    if worker in self.assigned_paths:
                        path, rate = self.assigned_paths[ worker ]

                        for i in range( len( path ) - 1 ):
                            edge = ( path[ i ], path[ i + 1 ] )

                            if edge in self.link_allocated_rate:
                                self.link_allocated_rate[ edge ] = max( 0.0, self.link_allocated_rate[ edge ] - rate )
                        
                        del self.assigned_paths[ worker ]

                self.purgeFlows( key )

                data[ "Round" ] = 0
                data[ "Workers" ].clear()
                data[ "Active_This_Round" ].clear()
                data[ "Worker_Bytes" ].clear()
                data[ "Dv" ] = 0
                data[ "Last_Dv" ] = 0
                data[ "Total_Accumulated_Bytes" ] = 0
                data[ "Duration" ] = 0
                data[ "Tv_Period" ] = 0.0
                data[ "Phase" ] = -1.0
                data[ "Current_Burst_Start" ] = 0.0
                data[ "Last_Real_Round_Start" ] = 0.0
                data[ "Last_Activity_Time" ] = current_time
                data[ "In_Burst" ] = False
                data[ "Silence_Count" ] = 0
                data[ "First_Packet_Time" ] = 0.0

        # Note: If ALL trainings are currently inactive, perform a complete global timer reset
        # This allows running multiple consecutive experiments without restarting the controller
        all_inactive = all( data[ "Phase" ] == -1.0 for data in self.trainings.values() )
        
        if all_inactive and self.first_burst_detected:
            self.first_burst_detected = False
            self.global_start_time = 0.0
            
            term_width = shutil.get_terminal_size((85, 15)).columns - 15
            log.info( "=" * term_width )
            log.info( "[SYSTEM] ALL EXPERIMENTS ARE CONCLUDED. GLOBAL TIMERS RESET." )
            log.info( "=" * term_width )

    def _handle_FlowStatsReceived( self, event ):
        
        # Purpose: It receives and analyzes OpenFlow statistics to calculate throughput and manage ML cycles

        current_time = time.time()
        
        for dst_ip in self.collectors:
            
            # Note: Edge polling mechanism to filter the indicators that allows to process only those coming from the switch directly connected to the destination element ( intermidiate devices are ignored )
            if dst_ip not in self.ip_to_location:
                continue

            dest_dpid = self.ip_to_location[ dst_ip ][ 0 ]

            if event.connection.dpid != dest_dpid:
                continue 
            
            training_data = self.trainings[ dst_ip ]
            t_name = self.collectors[ dst_ip ]
            bytes_difference = 0
            active_in_cycle = set()
            
            # Grouping bytes by source IP to prevent double counting of concurrent flows
            current_worker_bytes = {}

            for f in event.stats:
                if f.match.nw_src and f.match.nw_dst == dst_ip:
                    src_ip = str( f.match.nw_src )
                    current_worker_bytes[ src_ip ] = current_worker_bytes.get( src_ip, 0 ) + f.byte_count
            
            for src_ip, total_bytes in current_worker_bytes.items():
                last_b = training_data[ "Worker_Bytes" ].get( src_ip, 0 )
                
                # Handling OpenFlow rules timeout. If "byte_count" is zero, then computations start from "0"
                if total_bytes >= last_b:
                    diff = total_bytes - last_b
                else:
                    diff = total_bytes 
                    
                bytes_difference += diff
                training_data[ "Worker_Bytes" ][ src_ip ] = total_bytes
                
                if diff > 0:
                    active_in_cycle.add( src_ip )
                    training_data[ "Total_Accumulated_Bytes" ] += diff
                    
            time_difference = current_time - training_data[ "Last_Time" ]
            
            if time_difference > 0:
                throughput = bytes_difference / time_difference

                if throughput > ( self.burst * 0.05 ):
                    training_data[ "Last_Activity_Time" ] = current_time
                
                # If the rate exceeds the threshold, a burst occurs, raising an incast aggregation phase
                if throughput > self.burst: 
                    if not training_data[ "In_Burst" ]:
                        training_data[ "In_Burst" ] = True
                        
                        if not self.first_burst_detected:
                            self.first_burst_detected = True

                        training_data[ "Current_Burst_Start" ] = current_time
                        
                        if training_data[ "Phase" ] == -1.0:
                            training_data[ "Phase" ] = ( training_data[ "First_Packet_Time" ] - self.global_start_time ) + self.start_phi

                        training_data[ "Duration" ] = 0
                        training_data[ "Dv" ] = 0
                        training_data[ "Active_This_Round" ].clear()

                    # Updating the statistics
                    training_data[ "Silence_Count" ] = 0
                    training_data[ "Dv" ] += bytes_difference
                    training_data[ "Duration" ] += time_difference
                    training_data[ "Active_This_Round" ].update( active_in_cycle )

                else:
                    if training_data[ "In_Burst" ]:
                        training_data[ "Dv" ] += bytes_difference
                        training_data[ "Duration" ] += time_difference
                        training_data[ "Active_This_Round" ].update( active_in_cycle )
                        
                        training_data[ "Silence_Count" ] += 1
                        required_silence = max( 1, int( 2.0 / self.period ) )
                        
                        if training_data[ "Silence_Count" ] >= required_silence:
                            training_data[ "In_Burst" ] = False
                            training_data[ "Silence_Count" ] = 0
                            
                            d_v = training_data[ "Dv" ]
                            d_v_mb = d_v / 1000000.0  
                            
                            # Note: Ignore trivial TCP ACKs phantom rounds ( must be > 1 MB )
                            if d_v_mb > 1.0:
                                if training_data[ "Last_Real_Round_Start" ] > 0:
                                    gap = training_data[ "Current_Burst_Start" ] - training_data[ "Last_Real_Round_Start" ]
                                    
                                    if training_data[ "Tv_Period" ] == 0.0:
                                        training_data[ "Tv_Period" ] = gap
                                    else:
                                        training_data[ "Tv_Period" ] = ( gap * self.alpha ) + ( training_data[ "Tv_Period" ] * ( 1.0 - self.alpha ) )
                                
                                training_data[ "Last_Real_Round_Start" ] = training_data[ "Current_Burst_Start" ]
                                training_data[ "Round" ] += 1
                                
                                current_round = training_data[ "Round" ]
                                active_workers = list( training_data[ "Active_This_Round" ] )
                                k_v = len( active_workers )
                                t_v = training_data[ "Tv_Period" ]
                                phi_v = training_data[ "Phase" ]
                                duration = max(0.0, training_data[ "Duration" ] - (required_silence * self.period))

                                term_width = shutil.get_terminal_size((85, 15)).columns - 15
                
                                log.info( "-" * term_width )
                                log.info( "[%s] ROUND %d COMPLETED", t_name, current_round )
                                log.info( "[%s] Workers (K_v): %d -> %s", t_name, k_v, active_workers )
                                log.info( "[%s] Volume (D_v): %.2f MB", t_name, d_v_mb ) 
                                log.info( "[%s] Period (T_v): %.2f sec", t_name, t_v )
                                log.info( "[%s] Phase (Phi_v): %.2f sec", t_name, phi_v )
                                log.info( "[%s] Completion Time: %.2f sec", t_name, duration )
                                log.info( "-" * term_width )
                                
                                training_data[ "Last_Dv" ] = d_v

                                for worker in training_data[ "Workers" ]:
                                    if worker in self.assigned_paths:
                                        path, rate = self.assigned_paths[ worker ]
                                        
                                        for i in range( len( path ) - 1 ):
                                            edge = ( path[ i ], path[ i + 1 ] )
                                            if edge in self.link_allocated_rate:
                                                self.link_allocated_rate[ edge ] = max( 0.0, self.link_allocated_rate[ edge ] - rate )
                                        
                                        del self.assigned_paths[ worker ]
                                        
                                self.purgeFlows( dst_ip )

            training_data[ "Last_Time" ] = current_time

    # MODULE 4: Traffic Control & Routing 
    def installRoute( self, src_dpid, src_ip, dst_ip, training_data ):

        # Purpose: It computes shortest paths, applies Capacity-Awareness, and pushes symmetric flows to switches
        
        current_time = time.time()

        # Configuring the anti "Packet-In" storms mechanism is configured
        flow = ( src_ip, dst_ip )
        
        # If rules have already calculated and sent for the current flow in the last "period" seconds, block the request
        if flow in self.installed_flows:
            if current_time - self.installed_flows[ flow ] < self.period: 
                return

        # Later, an host tracking check is performed
        if dst_ip not in self.ip_to_location: 
            return
            
        dest_dpid, dest_port, _ = self.ip_to_location[ dst_ip ]

        # Note: The following statement avoids crashes if the topology is not yet fully formed
        if src_dpid not in self.topology or dest_dpid not in self.topology: 
            return

        path = ( src_dpid, dest_dpid )

        if path not in self.path_cache:
            k_paths = self.getUCMPRoutes( src_dpid, dest_dpid, k = self.k, cutoff = self.cutoff )

            if not k_paths: 
                return
            
            self.path_cache[ path ] = k_paths
            
        k_paths = self.path_cache[ path ]

        if not k_paths: 
            return

        t_name = self.collectors[ dst_ip ]

        # At this point, the "Capacity-Aware" engine is launched to provide a fair global balancing
        if src_ip in self.assigned_paths:
            selected_path = self.assigned_paths[ src_ip ][ 0 ]
        else:
            is_bootstrap = ( training_data.get( "Round", 0 ) == 0 )
            
            if is_bootstrap:
                # Using a simple Round-Robin based on the number of workers discovered so far
                num_workers_seen = len( training_data.get( "Workers", set() ) )
                selected_path = k_paths[ num_workers_seen % len( k_paths ) ]
                worker_expected_rate = 0.0
            else:
                # Starting from "ROUND 2" the true "Capacity-Aware" mechanism is applied
                active_set = training_data.get( "Active_This_Round", set() )
                K_v = len( active_set ) if len( active_set ) > 0 else len( training_data.get( "Workers", set() ) )
                K_v = max( 1, K_v )
                
                worker_expected_rate = self.capacity / float( K_v )
                selected_path = k_paths[ 0 ]
                min_bottleneck = float( "inf" )
                
                # Finding the least saturated path virtually
                for path in k_paths:
                    path_bottleneck = 0.0

                    for i in range( len( path ) - 1 ):
                        edge = ( path[ i ], path[ i + 1 ] )
                        current_load = self.link_allocated_rate.get( edge, 0.0 )
                        saturation = ( ( current_load + worker_expected_rate ) / float( self.capacity ) ) * 100
                        
                        if saturation > path_bottleneck: 
                            path_bottleneck = saturation
                    
                    if path_bottleneck < min_bottleneck:
                        min_bottleneck = path_bottleneck
                        selected_path = path

            # Updating the network balance
            for i in range( len( selected_path ) - 1 ):
                edge = ( selected_path[ i ], selected_path[ i + 1 ] )
                self.link_allocated_rate[ edge ] = self.link_allocated_rate.get( edge, 0.0 ) + worker_expected_rate

            self.assigned_paths[ src_ip ] = ( selected_path, worker_expected_rate )
            hex_path = [ dpid_to_str( node ) for node in selected_path ]
            
            if is_bootstrap:
                log.info( "[%s] ROUTING | %s -> %s | Path: %s", t_name, src_ip, dst_ip, hex_path )
            else:
                log.info( "[%s] ROUTING | %s -> %s | Path: %s | Saturation: %5.2f%%", t_name, src_ip, dst_ip, hex_path, min_bottleneck )

        # The function ends with:
        # -) installing ofp_flow_mod along all intermediate nodes of the route
        for i in range( len( selected_path ) - 1 ):
            current_node = selected_path[ i ]
            next_node = selected_path[ i + 1 ]

            out_port = self.topology[ current_node ][ next_node ]
            
            self.sendFlowMod( current_node, src_ip, dst_ip, out_port )
        
        # -) storing the last rule on the switch that connects directly to the collector
        self.sendFlowMod( dest_dpid, src_ip, dst_ip, dest_port )
        
        # -) applying the same mechanism but considering the return route ( ACK )
        if src_ip in self.ip_to_location:
            src_dpid_loc, src_port_loc, _ = self.ip_to_location[ src_ip ]
            reversed_path = selected_path[::-1] 
            
            for i in range( len( reversed_path ) - 1 ):
                current_node = reversed_path[ i ]
                next_node = reversed_path[ i + 1 ]
                
                out_port = self.topology[ current_node ][ next_node ]
                
                self.sendReverseFlowMod( current_node, dst_ip, src_ip, out_port )
                
            self.sendReverseFlowMod( src_dpid_loc, dst_ip, src_ip, src_port_loc )
        
        self.installed_flows[ flow ] = current_time

    def sendReverseFlowMod( self, dpid, src_ip, dst_ip, out_port ):
        
        # Purpose: It creates and sends the symmetric return OpenFlow "Flow-Mod" message
        
        connection = core.openflow.getConnection( dpid )
        
        if not connection: 
            return
            
        msg = of.ofp_flow_mod() 
        msg.priority = 100
        msg.match.dl_type = 0x0800 
        msg.match.nw_src = src_ip # Source IP ( Collector )
        msg.match.nw_dst = dst_ip # Destination IP ( Worker )
        msg.idle_timeout = self.inactivity 
        msg.hard_timeout = self.hard 
        msg.actions.append( of.ofp_action_output( port = out_port ) ) 
        connection.send( msg )

    def sendFlowMod( self, dpid, src_ip, dst_ip, out_port ):
        
        # Purpose: It creates and sends the primary OpenFlow "Flow-Mod" message
        
        connection = core.openflow.getConnection( dpid )
        
        if not connection: 
            return
            
        msg = of.ofp_flow_mod() 
        msg.priority = 100 
        msg.match.dl_type = 0x0800 
        msg.match.nw_src = src_ip # Source IP ( Worker )
        msg.match.nw_dst = dst_ip # Destination IP ( Collector )
        msg.idle_timeout = self.inactivity 
        msg.hard_timeout = self.hard 
        msg.actions.append( of.ofp_action_output( port = out_port ) ) 
        connection.send( msg )

def launch( alpha = 0.25, burst = 100000, capacity = 12500000, collectors = "10.0.1.1:Training_Blue,10.0.1.2:Training_Green,10.0.1.3:Training_Red,10.0.1.4:Training_Yellow", cutoff = 3, hard = 0, inactivity = 120, k = 2, period = 1, stability = 15, start_phi = 1.0 ):
    
    # Purpose: It represents the POX entry point. Parameters can be injected using the command line
    
    core.registerNew( Project_1, alpha, burst, capacity, collectors, cutoff, hard, inactivity, k, period, stability, start_phi )